### PR TITLE
employees table DOM

### PR DESCRIPTION
**Pull request by Yaroslav65**
- DEMO LINK - https://Yaroslav65.github.io/js_employees_table_DOM/

### CODE REVIEW

**Review by SanyaBratashchuk — CHANGES_REQUESTED** [review]
salary cannot be negative 
image

**Comment by Yaroslav65** [comment]
> salary cannot be negative image

Hi i have some problems with commits please check commit with hash number - [008d71b]

**Review by vadiimvooo — APPROVED** [review]
LGTM

**Comment by Yaroslav65** [comment]
> LGTM

Hi i have some problems with commits please tell me how me fix that?

**Pull request closed without merging**
